# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'searchPic&People' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for searchPic&People
  pod 'Toast-Swift', '~> 5.0.1'

end
